### ISSUE TITLE
Send funds COW funds to delegate

### ISSUE THREAD

**Issue by josojo** [bh2smith/cow-solver-rewards#13]
Felix wrote:
>While technically the solver EOAs are directly entitled for the reward, it makes sense to directly transfer all rewards to the GP Team’s Safe for further disbursement (can be seen like a delegate).

We need to take of that.
The address should be: https://gnosis-safe.io/app/eth:0x6C642caFCbd9d8383250bb25F67aE409147f78b2/balances

**Comment by bh2smith** [comment]
This has been discussed with anna already in the sync. We concluded that we would send to the solvers directly to make it easier to see solver stats. However also, eventually we would need to write a delegation smart contract to redirect transfers.

**Comment by josojo** [comment]
Why have you guys concluded it? What are the reason for it? I see one huge disadvantage: In order to collect the cows, we need to use get the PK out of the prod enviorment. And hence only a few people can do it and it has quite some overhead. Additionally, the gas overhead is also existing.

**Comment by bh2smith** [comment]
Just a few points we considered

1. Solvers would require fewer topups if they were reimbursed for their gas costs directly. 
2. It is not correct to redirect funds in this project until we have an on chain delegation contract. 

COW tokens would be collected by solvers themselves and then we would have on chain stats for solver performace (based on their cow balance). Of course this isn't a huge issue since we can easily measure solver performance in other ways.

**Comment by annamsgeorge** [comment]
If there are strong reasons to send them to the Safe instead, then it's fine. However, optic wise it looks better to send them to the individual solvers. It would also help us to publicly show how many rewards different solvers have been making. It looks more decentralized, and anyways is the way forward, once we have external solvers participating we have to send the COW to their EOAs. Not realizing that there's a preference to send it directly to the Safe, I had discussed sending the funds to the different EOAs with Martin yesterday and he didn't mind + agreed that optics look better. But again, if there are strong reasons to do it otherwise, then I guess it's also fine, it just weakens our narrative a bit.

**Comment by bh2smith** [comment]
One the delegation contracts are in place then I would think it makes plenty of sense to respect the on-chain delegation and redirect the funds if the solver chooses to do so. Up until that point, I feel quite strongly about sending them to the solvers themselves:

- correctness
- having to top up solvers with gas money less often

**Comment by josojo** [comment]
@nlordell
Can you give us some insights on how hard it will be to withdraw the COWs later one from the production addresses? Probably, we will only do that in a future, but if it compromises security settings in some way, I would be against it.
I think it all depends on the future setup of the production Private Key security rules.

**Comment by nlordell** [comment]
> @nlordell

I think because this repo is under `bh2smith` and not the `gnosis` org, the notifications get sent to my personal e-mail and not my work e-mail.

So sorry I didn't see this until now 🙈.

> but if it compromises security settings in some way, I would be against it.

I don't think so. We just need to add ["transaction validation rules"](https://github.com/gnosis/hdnode/blob/main/validators/cowswap.lua) for allowing the accounts to execute `CowToken.transfer` where the recipient is some Gnosis account.

**Comment by josojo** [comment]
Ups.
Why is this repo in bh2smith? Let's keep it that way, until we have the new cow github repo.

**Comment by bh2smith** [comment]
> Why is this repo in bh2smith? Let's keep it that way, until we have the new cow github repo.

This is exactly the reason why. We are no longer creating new repos in gnosis.
